# Generated by Django 4.2.30 on 2026-06-05 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0003_backfill_domain_fqdn_reversed'),
        ('owners', '0003_backfill_managementunit_fqdn_reversed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_fqdn', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '申請済み'), ('reviewing', 'レビュー中'), ('review_complete', '最終承認待ち'), ('approved', '承認済み'), ('rejected', '棄却')], default='draft', max_length=20)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_requests', to='domains.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_requests', to='domains.company')),
                ('domain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='domains.domain')),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='owners.employee')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to='owners.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainRequestReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('brand', 'ブランドチェック'), ('ip_trademark', '知財チェック')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '未対応'), ('approved', '承認'), ('rejected', '棄却')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('auto_judgment', models.BooleanField(blank=True, null=True)),
                ('auto_judgment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='requests.domainrequest')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='owners.employee')),
            ],
            options={
                'ordering': ['review_type'],
                'unique_together': {('request', 'review_type')},
            },
        ),
    ]
