# Generated by Django 4.2.30 on 2026-06-05 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(choices=[('acquire', 'acquire'), ('retire', 'retire'), ('owner_change', 'owner_change'), ('registrar_transfer', 'registrar_transfer'), ('brand_decision', 'brand_decision')], max_length=30)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_comment', models.TextField(blank=True)),
                ('brand_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_reviewed_approvals', to='owners.employee')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_approvals', to='owners.employee')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='domains.domain')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to='owners.employee')),
            ],
        ),
    ]
