# Generated by Django 4.2.30 on 2026-06-05 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registrar_name', models.CharField(blank=True, max_length=255)),
                ('registrant_name', models.CharField(blank=True, max_length=255)),
                ('renewal_method', models.CharField(blank=True, choices=[('auto', '自動'), ('manual', '手動')], max_length=20)),
                ('transfer_allowed', models.BooleanField(blank=True, null=True)),
                ('renewal_deadline', models.DateField(blank=True, null=True)),
                ('renewal_notify_to', models.EmailField(blank=True, max_length=254)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_contracts', to='owners.department')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_contract', to='domains.domain')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_registrar_contracts', to='owners.employee')),
            ],
        ),
    ]
