# Generated by Django 4.2.30 on 2026-06-05 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('own', '自社'), ('group', 'グループ会社'), ('affiliate', '関連会社')], default='own', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company_code'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('trademark_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='domains.company')),
            ],
            options={
                'ordering': ['brand_code'],
            },
        ),
        migrations.CreateModel(
            name='DomainHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('domain', 'ドメイン'), ('registrar', 'レジストラ'), ('dns', 'DNS'), ('certificate', '証明書'), ('security', 'セキュリティ'), ('owner', '管理責任'), ('risk', 'リスク'), ('inventory', '棚卸'), ('approval', '承認'), ('lifecycle', 'ライフサイクル')], max_length=30)),
                ('target_id', models.UUIDField()),
                ('change_category', models.CharField(max_length=20)),
                ('change_type', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('manual', '手動'), ('auto', '自動')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('diff_json', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_histories', to='owners.employee')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_hist_target'), models.Index(fields=['changed_at'], name='idx_hist_changed_at')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('gtld', 'gTLD'), ('cctld', 'ccTLD'), ('subdomain', 'サブドメイン')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('active', '利用中'), ('expired', '失効疑い'), ('deleted', '廃止')], max_length=20)),
                ('mgmt_category', models.CharField(choices=[('managed', '管理対象'), ('individual', '個別管理対象')], max_length=20)),
                ('registered_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('renewal_policy', models.CharField(blank=True, choices=[('auto', '自動更新'), ('manual', '手動更新'), ('none', '更新なし')], max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('used_service', models.CharField(blank=True, max_length=255)),
                ('public_site', models.URLField(blank=True)),
                ('mail_enabled', models.BooleanField(default=False)),
                ('redirect_enabled', models.BooleanField(default=False)),
                ('external_linked', models.BooleanField(default=False)),
                ('use_start_at', models.DateField(blank=True, null=True)),
                ('use_end_planned_at', models.DateField(blank=True, null=True)),
                ('brand_protection_note', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='domains.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='domains.company')),
                ('management_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='owners.managementunit')),
                ('parent_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdomains', to='domains.domain')),
            ],
            options={
                'ordering': ['fqdn'],
                'indexes': [models.Index(fields=['management_unit'], name='idx_domains_unit'), models.Index(fields=['parent_domain'], name='idx_domains_parent'), models.Index(fields=['status'], name='idx_domains_status'), models.Index(fields=['expires_at'], name='idx_domains_expires'), models.Index(fields=['brand'], name='idx_domains_brand')],
            },
        ),
    ]
