# Generated by Django 4.2.30 on 2026-06-07 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0003_backfill_domain_fqdn_reversed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('scheduled', '定期'), ('manual', '手動'), ('retry', '再実行'), ('fixture', 'テスト')], max_length=20)),
                ('requested_types', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('partial', 'partial'), ('failed', 'failed'), ('canceled', 'canceled')], default='queued', max_length=20)),
                ('priority', models.CharField(choices=[('normal', '通常'), ('high', '高')], default='normal', max_length=20)),
                ('dedup_key', models.CharField(max_length=255, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_jobs', to='domains.domain')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('dns_records', 'dns_records'), ('mail_auth', 'mail_auth'), ('certificate', 'certificate'), ('registration', 'registration'), ('http_status', 'http_status'), ('security_summary', 'security_summary')], max_length=30)),
                ('method', models.CharField(max_length=30)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('succeeded', 'succeeded'), ('failed', 'failed'), ('skipped', 'skipped')], max_length=20)),
                ('observed_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('raw_summary', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('changed', models.BooleanField(default=False)),
                ('diff_json', models.JSONField(blank=True, default=dict)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_results', to='domains.domain')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='collection_jobs.collectionjob')),
            ],
            options={
                'ordering': ['-observed_at', '-collected_at'],
                'indexes': [models.Index(fields=['domain', 'result_type', 'observed_at'], name='idx_collect_result_domain_type'), models.Index(fields=['status', 'observed_at'], name='idx_collect_result_status')],
            },
        ),
        migrations.AddIndex(
            model_name='collectionjob',
            index=models.Index(fields=['domain', 'requested_at'], name='idx_collection_job_domain_time'),
        ),
        migrations.AddIndex(
            model_name='collectionjob',
            index=models.Index(fields=['status', 'priority', 'requested_at'], name='idx_collection_job_queue'),
        ),
    ]
