# Generated by Django 4.2.30 on 2026-06-05 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_fqdn', models.CharField(max_length=255)),
                ('san', models.TextField(blank=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('issue_method', models.CharField(blank=True, choices=[('acme', 'ACME'), ('manual', '手動'), ('outsourced', '外部委託')], max_length=20)),
                ('renewal_method', models.CharField(blank=True, choices=[('acme', 'ACME'), ('manual', '手動'), ('outsourced', '外部委託')], max_length=20)),
                ('used_system', models.CharField(blank=True, max_length=255)),
                ('manager_contact', models.CharField(blank=True, max_length=255)),
                ('ct_detected', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='domains.domain')),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='idx_cert_domain'), models.Index(fields=['expires_at'], name='idx_cert_expires'), models.Index(fields=['ct_detected'], name='idx_cert_ct')],
            },
        ),
    ]
