# Generated by Django 4.2.30 on 2026-06-05 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('TXT', 'TXT')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='domains.domain')),
            ],
            options={
                'ordering': ['domain', 'record_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DnsInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_servers', models.TextField(blank=True)),
                ('dns_service', models.CharField(blank=True, max_length=255)),
                ('dnssec_enabled', models.BooleanField(blank=True, null=True)),
                ('spf_status', models.CharField(blank=True, choices=[('set', '設定済'), ('unset', '未設定'), ('invalid', '不正')], max_length=20)),
                ('dkim_status', models.CharField(blank=True, choices=[('set', '設定済'), ('unset', '未設定'), ('invalid', '不正')], max_length=20)),
                ('dmarc_status', models.CharField(blank=True, choices=[('set', '設定済'), ('unset', '未設定'), ('invalid', '不正')], max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dns_info', to='domains.domain')),
            ],
        ),
    ]
