# Generated by Django 4.2.30 on 2026-06-05 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dnssec', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('registry_lock', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('registrar_lock', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('mfa', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('takeover_protection', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('cert_expiry_protection', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('mail_spoofing_protection', models.CharField(blank=True, choices=[('enabled', '有効'), ('disabled', '無効'), ('unknown', '不明')], max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_status', to='domains.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('expiry', '失効'), ('misconfig', '設定不備'), ('takeover', 'サブドメインテイクオーバー'), ('spoofing', 'なりすまし'), ('brand', 'ブランド'), ('owner_absent', '担当者不在'), ('cert_expiry', '証明書期限'), ('dnssec_unset', 'DNSSEC未設定'), ('dmarc_unset', 'DMARC未設定')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('info', 'info')], max_length=10)),
                ('source', models.CharField(choices=[('auto', '自動'), ('manual', '手動')], max_length=20)),
                ('detected_at', models.DateField()),
                ('remediation_policy', models.TextField(blank=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('confirming', 'confirming'), ('closed', 'closed')], max_length=20)),
                ('closed_result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to='owners.employee')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='domains.domain')),
                ('management_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='owners.managementunit')),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='idx_risk_domain'), models.Index(fields=['status', 'severity'], name='idx_risk_status_sev'), models.Index(fields=['due_at'], name='idx_risk_due')],
            },
        ),
    ]
