# Generated by Django 4.2.30 on 2026-06-05 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_fqdn', models.CharField(max_length=255)),
                ('detection_type', models.CharField(choices=[('similar', 'similar'), ('spoofing', 'spoofing'), ('trademark', 'trademark'), ('other', 'other')], max_length=20)),
                ('source', models.CharField(choices=[('auto', '自動'), ('manual', '手動')], max_length=20)),
                ('detected_at', models.DateField()),
                ('whois_json', models.JSONField(blank=True, null=True)),
                ('confirm_status', models.CharField(choices=[('unconfirmed', 'unconfirmed'), ('confirming', 'confirming'), ('judged', 'judged')], max_length=20)),
                ('action_judgment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_targets', to='domains.brand')),
            ],
        ),
    ]
