# Generated by Django 4.2.30 on 2026-06-05 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_name_full', models.CharField(blank=True, max_length=255)),
                ('level', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('honbu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honbu_departments', to='owners.department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='owners.department')),
            ],
            options={
                'ordering': ['dept_code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name_kana', models.CharField(max_length=100)),
                ('given_name_kana', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('registered_domain', '登録ドメイン'), ('dns_zone', 'DNSゾーン'), ('subdomain_namespace', 'サブドメイン名前空間')], max_length=30)),
                ('unit_name', models.CharField(max_length=255, unique=True)),
                ('setting_type', models.CharField(choices=[('individual', '個別設定'), ('inherited', '継承'), ('provisional', '暫定設定')], max_length=20)),
                ('promotion_reasons', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('last_inventory_at', models.DateField(blank=True, null=True)),
                ('next_check_at', models.DateField(blank=True, null=True)),
                ('check_status', models.CharField(blank=True, choices=[('confirmed', '確認済'), ('requested', '確認依頼中'), ('unanswered', '未回答'), ('returned', '差戻し'), ('needs_fix', '要是正'), ('retire_candidate', '廃止候補')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dns_zone_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dns_zone_units', to='owners.employee')),
                ('inherited_from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inheriting_units', to='owners.managementunit')),
                ('mgmt_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_units', to='owners.department')),
                ('mgmt_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to='owners.employee')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='owners.managementunit')),
                ('primary_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_units', to='owners.employee')),
                ('secondary_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_units', to='owners.employee')),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_type', models.CharField(choices=[('periodic', '定期棚卸'), ('adhoc', '都度確認')], max_length=20)),
                ('requested_at', models.DateField()),
                ('due_at', models.DateField(blank=True, null=True)),
                ('check_status', models.CharField(choices=[('confirmed', '確認済'), ('requested', '確認依頼中'), ('unanswered', '未回答'), ('returned', '差戻し'), ('needs_fix', '要是正'), ('retire_candidate', '廃止候補')], max_length=20)),
                ('detected_diff_json', models.JSONField(blank=True, null=True)),
                ('answer_json', models.JSONField(blank=True, null=True)),
                ('answered_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_inventories', to='owners.employee')),
                ('management_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='owners.managementunit')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee2Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.employee')),
            ],
            options={
                'ordering': ['employee_id', 'department_id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='employees', through='owners.Employee2Department', to='owners.department'),
        ),
        migrations.AddIndex(
            model_name='managementunit',
            index=models.Index(fields=['parent_unit'], name='idx_unit_parent'),
        ),
        migrations.AddIndex(
            model_name='managementunit',
            index=models.Index(fields=['mgmt_dept'], name='idx_unit_dept'),
        ),
        migrations.AddIndex(
            model_name='managementunit',
            index=models.Index(fields=['next_check_at'], name='idx_unit_nextcheck'),
        ),
        migrations.AddIndex(
            model_name='employee2department',
            index=models.Index(fields=['department'], name='idx_emp2dept_dept'),
        ),
        migrations.AddIndex(
            model_name='employee2department',
            index=models.Index(fields=['employee', 'is_primary'], name='idx_emp2dept_primary'),
        ),
        migrations.AlterUniqueTogether(
            name='employee2department',
            unique_together={('employee', 'department')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['family_name', 'given_name'], name='idx_emp_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['family_name_kana', 'given_name_kana'], name='idx_emp_kana'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='idx_emp_active'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='idx_dept_parent'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['honbu'], name='idx_dept_honbu'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='idx_dept_active'),
        ),
    ]
