# Generated by Django 4.2.30 on 2026-06-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementunit',
            name='fqdn_reversed',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
